# A generic, single-database configuration.

[alembic]
# path to migration scripts
script_location = db:migrations

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# file_template = %%(rev)s_%%(slug)s

# timezone to use when rendering the date within the migration file as
# well as the filename.
# If specified, the value is passed to datetime.datetime.now().
# If not specified, the value is UTC.
# timezone =

# max length of 'slug' field
# truncate_slug_length = 40

# set to 'true' to run the environment during the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc files to be created
# sourceless = false

# version location specification; This defaults to db/migrations/versions.
# When using multiple version directories, filenames must be unique.
# version_locations = %(here)s/db/migrations/versions

# the output encoding used when revision files are written from script.py.mako
# output_encoding = utf-8

sqlalchemy.url = sqlite:///./accounting.db

[post_write_hooks]
# post_write_hooks allows scripts to be run after generating a revision file.
# See http://alembic.zzzcomputing.com/en/latest/api/runtime.html#post-write-hooks for details.

[logging]
default_handler = console
log_file = alembic.log

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
